### ISSUE TITLE
Issue installing b2-master/python

### ISSUE THREAD

**Issue by PB12345** [bertiniteam/b2#30]
Hi,

I get an error trying to execute the make command to install the python library of b2. The terminal output and my system information is attached. I have installed boost 1.61 and Eigen3.

Do you need any other information?

It would be awesome, if you could find out what's wrong :)

[error1.txt](https://github.com/bertiniteam/b2/files/282176/error1.txt)
![bildschirmfoto vom 2016-05-25 14 10 31](https://cloud.githubusercontent.com/assets/19520449/15543202/4f9313d4-2294-11e6-81c2-117c33f03be4.png)

**Comment by ofloveandhate** [comment]
i am first working on solving problems for `make check` for the core.  Then I will try compiling the Python bindings.  I am still puzzled as to why code was compiling for me before the update to b2-2.0.0-alpha4 on bertiniteam, and now fails.  🎱  clearly i need to understand the compiler and library version interactions better.  thanks for being patient as we work through this!

--

there appear to be several issues going on right now.  this note describes the issue with `max()`.

with eigen 3.2.x, and Boost < (not equal to) 1.61, there is a problem with svd and the max function...  i have worked with John with Boost.Multiprecision and Gael with Eigen on this issue before.  The issue stems from the way Eigen 3.2.x calls max().   see [this boost ticket](https://svn.boost.org/trac/boost/ticket/11149).  Essentially, the lookup of `max` fails, and there are several fixes.  

1. use eigen 3.3-beta1.  the lookup of max succeeds.
2.  patch boost versions 1.60.x and before using to [this patch](https://github.com/boostorg/multiprecision/commit/f57bd6b31a64787425ec891bd2ceb536c9036f72).  this patch is applied as of 1.61.
3.  use boost >= 1.61.  this should solve the max() problem.

--

having solved the max() problem as above, i am experiencing issues with scalar multiplication by integers, getting ambiguous lookup.  this occurs with eigen 3.3-beta1, which is the current stable development release.  i do not yet know how to solve this problem.  maybe it should be reported to Eigen devs?  i'm not yet ready to report it...

--

i will now try various combinations of Boost versions and patches, along with Eigen versions, and see what I can get to compile.  I guess this is the result of using heavily templated code, and bleeding edge libraries like Eigen.  I remain satisfied in my choice of dependencies, however, and thank you for helping Bertini 2 to succeed by testing these early versions.

**Comment by ofloveandhate** [comment]
Having patched Boost 1.58 (4 modifications -- modding detail/default_ops, adding detail/min_max.hpp, and copying traits/is_backend.hpp from 1.61, uncomment lines in core/include/bertini2/mpfr_extensions.hpp), I was able to make both the tests (`make check`) and python bindings on ubuntu 14.04 LTS, using GCC 4.9.3, Eigen 3.2.8.  Note that some tests are currently expected to fail :(.   These will be corrected in an upcoming release.

next i will again try Boost 1.61 against Eigen 3.2.8, Ubuntu 14.04, GCC 4.9.3.  Since Mint essentially lives atop Ubuntu, I hope this carries forward to your Mint install.  My VM with Mint 17.3 isn't building Boost.Python correctly right now, so have not tested directly in Mint yet.

**Comment by ofloveandhate** [comment]
I was able to build the python bindings in Mint 17.3 with Boost 1.61, and the Eigen from apt-get, gcc 4.9.3.  Tests all ran successfully.  @PB12345  Can you confirm?
![virtualbox_minty_31_05_2016_16_47_17](https://cloud.githubusercontent.com/assets/1388063/15689989/5e51f8f8-274f-11e6-9958-5ddb75f40ad9.png)

**Comment by ofloveandhate** [comment]
While the above does get the python bindings compiling, it still does not address the failing eigen_test.cpp compilation.  Working on that now.

**Comment by PB12345** [comment]
Hi,

many thanks for the quick reply.

I can not confirm. I still get the 

**make[1]: *** [src/pybertini_la-endgame_export.lo] Fehler 1**

error. 
[error.txt](https://github.com/bertiniteam/b2/files/295202/error.txt)

**Comment by ofloveandhate** [comment]
the previous comments did not address the issue you raised, @PB12345 .  i believe that I have addressed the issue as of this time.  the problem was the use of the `auto` keyword, rather than the specific type, so the compiler was deducing a type which was not << streamable...  Please take a pull, re-compile and install the core, and then re-compile python.  i believe it will work this time. 

#32 specifically addresses this issue, and several others.

**Comment by PB12345** [comment]
Yeah, it worked. I could install everything.

**Comment by ofloveandhate** [comment]
ok, great.  thanks! go ahead and close if you feel appropriate.

**Comment by rideckard** [comment]
Hello,

Maybe I can add some additional Information. I have boost 1.61, gmp-6.1.0 and mpfr-4.1.4 using ubuntu 14.04 with g++ 4.9.3.
I don't know if you allready solved the issue but I also failed to compile the tests with Eigen 3.3-beta1, 
the compiler complaining about "ambiguous overload for ‘operator*’". With Eigen 3.2.8 all the tests compiled (though some failed).
I reproduced the failure with this working example from eigen_test.cpp:
```
 #include <iostream>
 #include <Eigen/Dense>
 #include "eigen_extensions.hpp"

 int main() {
 using data_type = bertini::mpfr;
 int a = 2;

 Eigen::Matrix<data_type, Eigen::Dynamic, Eigen::Dynamic> M(2,2);
 M << data_type(1), data_type(2), data_type(1), data_type(2);
 M = M*3; 
 M = a*M; //works 
 }
```
The left multiplication works but not the right. Here is the log of the test suite (with Eigen 3.2.8)
[test-suite.log.txt](https://github.com/bertiniteam/b2/files/308818/test-suite.log.txt) Are these the expected fails?

**Comment by ofloveandhate** [comment]
those are indeed the expected fails.  i have asked for support from the Eigen community, and one of the developers responded: https://forum.kde.org/viewtopic.php?f=74&t=133221

I suggest you take a checkout of the unstable dev branch of eigen, and according to ggael, things should be good to go.  let me know if you give this a try, and how it goes!  i have not yet tried it myself, but will soon.

**Comment by ofloveandhate** [comment]
I checked out the latest Eigen dev, and while it does indeed fix the issue regarding these ambiguous overloads, there is a new problem with the ceil and abs functions, and the way they are called.  i refer again to [the kde forum post](https://forum.kde.org/viewtopic.php?f=74&t=133221).  awaiting further response from ggael.  Eigen 3.3 dev does not compile Bertini2 at this time.

**Comment by rideckard** [comment]
I can confirm, that the issue with the overload was fixed with the commit from ggael and I also see the problem with the ceil function. I checked out the parent commit and it had both problems so it doesnt seem related.

**Comment by bertiniteam** [comment]
calling this one fixed, and closing.
